### ISSUE TITLE
IOS 暢順，ANDROID 出現CRASH

### ISSUE THREAD

**Issue by wilson0506** [MEnigma/flutter_rtmp#10]

**Comment by wilson0506** [comment]
/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.flutterapplive, PID: 10186
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutterapplive-qZnPLssKmWPtyrsSHZuhPQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutterapplive-qZnPLssKmWPtyrsSHZuhPQ==/lib/arm, /data/app/com.example.flutterapplive-qZnPLssKmWPtyrsSHZuhPQ==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by wilson0506** [comment]
這個ANDROID用 SRS(Simple-RTMP-Server) 
https://github.com/PonnamKarthik/FlutterRtmpPlublisher
