### ISSUE TITLE
集成0.1.6报错

### ISSUE THREAD

**Issue by muzhis** [MEnigma/flutter_rtmp#13]
I/System.out(26667): >> TTT ------------------------------------------------------------------------
I/System.out(26667): >> [Flutter RTMP] startLive --> param : {url=rtmp://zhibo.shipinchao.com/kangfudaxue/001?auth_key=***********}
I/SrsFlvMuxer(26667): worker: connecting to RTMP server by url=rtmp://zhibo.shipinchao.com/kangfudaxue/001?auth_key=****
I/OMXClient(26667): Treble IOmx obtained
W/ExtendedACodec(26667): Failed to get extension for extradata parameter
I/OMXClient(26667): Treble IOmx obtained
I/ExtendedACodec(26667): setupVideoEncoder()
W/OMXUtils(26667): do not know color format 0x7fa30c06 = 2141391878
W/OMXUtils(26667): do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils(26667): do not know color format 0x7fa30c00 = 2141391872
W/OMXUtils(26667): do not know color format 0x7fa30c09 = 2141391881
W/OMXUtils(26667): do not know color format 0x7fa30c0a = 2141391882
W/OMXUtils(26667): do not know color format 0x7fa30c08 = 2141391880
W/OMXUtils(26667): do not know color format 0x7fa30c07 = 2141391879
W/OMXUtils(26667): do not know color format 0x7f000789 = 2130708361
E/ACodec  (26667): [OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
E/ACodec  (26667): [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
E/ACodec  (26667): signalError(omxError 0x80001001, internalError -1010)
E/MediaCodec(26667): Codec reported err 0xfffffc0e, actionCode 0, while in state 3
E/MediaCodec(26667): configure failed with err 0xfffffc0e, resetting...
I/OMXClient(26667): Treble IOmx obtained
E/MethodChannel#holo#cameraSettingConfig(26667): Failed to handle method call
E/MethodChannel#holo#cameraSettingConfig(26667): android.media.MediaCodec$CodecException: Error 0xfffffc0e
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.media.MediaCodec.native_configure(Native Method)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.media.MediaCodec.configure(MediaCodec.java:1950)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.media.MediaCodec.configure(MediaCodec.java:1873)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at net.ossrs.yasea.SrsEncoder.start(SrsEncoder.java:163)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:149)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:177)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at holo.mark.flutter_rtmp.RtmpManagerV2.startLive(rtmp.kt:146)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at holo.mark.flutter_rtmp.RtmpManagerV2.onMethodCall(rtmp.kt:77)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.os.Looper.loop(Looper.java:149)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at android.app.ActivityThread.main(ActivityThread.java:6842)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#holo#cameraSettingConfig(26667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
E/flutter (26667): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Error 0xfffffc0e, null)
E/flutter (26667): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (26667): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (26667): <asynchronous suspension>
E/flutter (26667): #2      RtmpManager.startLive (package:flutter_rtmp/src/rtmp_manager.dart:46:30)
E/flutter (26667): #3      _LiveTrmpContentState.build.<anonymous closure> (package:healthvideo/moudle/livestream/view/live_trmp_page.dart:83:34)
E/flutter (26667): #4      _RawChipState._handleTap (package:flutter/src/material/chip.dart:1653:23)
E/flutter (26667): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (26667): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (26667): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (26667): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (26667): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (26667): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (26667): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (26667): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (26667): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (26667): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (26667): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (26667): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (26667): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (26667): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (26667): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (26667): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (26667): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (26667): #22     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (26667): #23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (26667): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (26667): #25     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (26667): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (26667): 
W/AMessage(26667): failed to deliver message as target handler 4 is gone.

点击开始之后出现这个报错,并且无法推流
手机  魅族16th    android 8.1 系统

**Comment by MEnigma** [comment]
> I/System.out(26667): >> TTT ------------------------------------------------------------------------
> I/System.out(26667): >> [Flutter RTMP] startLive --> param : {url=rtmp://zhibo.shipinchao.com/kangfudaxue/001?auth_key=***********}
> I/SrsFlvMuxer(26667): worker: connecting to RTMP server by url=rtmp://zhibo.shipinchao.com/kangfudaxue/001?auth_key=****
> I/OMXClient(26667): Treble IOmx obtained
> W/ExtendedACodec(26667): Failed to get extension for extradata parameter
> I/OMXClient(26667): Treble IOmx obtained
> I/ExtendedACodec(26667): setupVideoEncoder()
> W/OMXUtils(26667): do not know color format 0x7fa30c06 = 2141391878
> W/OMXUtils(26667): do not know color format 0x7fa30c04 = 2141391876
> W/OMXUtils(26667): do not know color format 0x7fa30c00 = 2141391872
> W/OMXUtils(26667): do not know color format 0x7fa30c09 = 2141391881
> W/OMXUtils(26667): do not know color format 0x7fa30c0a = 2141391882
> W/OMXUtils(26667): do not know color format 0x7fa30c08 = 2141391880
> W/OMXUtils(26667): do not know color format 0x7fa30c07 = 2141391879
> W/OMXUtils(26667): do not know color format 0x7f000789 = 2130708361
> E/ACodec (26667): [OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
> E/ACodec (26667): [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
> E/ACodec (26667): signalError(omxError 0x80001001, internalError -1010)
> E/MediaCodec(26667): Codec reported err 0xfffffc0e, actionCode 0, while in state 3
> E/MediaCodec(26667): configure failed with err 0xfffffc0e, resetting...
> I/OMXClient(26667): Treble IOmx obtained
> E/MethodChannel#holo#cameraSettingConfig(26667): Failed to handle method call
> E/MethodChannel#holo#cameraSettingConfig(26667): android.media.MediaCodec$CodecException: Error 0xfffffc0e
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.media.MediaCodec.native_configure(Native Method)
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.media.MediaCodec.configure(MediaCodec.java:1950)
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.media.MediaCodec.configure(MediaCodec.java:1873)
> E/MethodChannel#holo#cameraSettingConfig(26667): at net.ossrs.yasea.SrsEncoder.start(SrsEncoder.java:163)
> E/MethodChannel#holo#cameraSettingConfig(26667): at net.ossrs.yasea.SrsPublisher.startEncode(SrsPublisher.java:149)
> E/MethodChannel#holo#cameraSettingConfig(26667): at net.ossrs.yasea.SrsPublisher.startPublish(SrsPublisher.java:177)
> E/MethodChannel#holo#cameraSettingConfig(26667): at holo.mark.flutter_rtmp.RtmpManagerV2.startLive(rtmp.kt:146)
> E/MethodChannel#holo#cameraSettingConfig(26667): at holo.mark.flutter_rtmp.RtmpManagerV2.onMethodCall(rtmp.kt:77)
> E/MethodChannel#holo#cameraSettingConfig(26667): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
> E/MethodChannel#holo#cameraSettingConfig(26667): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> E/MethodChannel#holo#cameraSettingConfig(26667): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.os.MessageQueue.next(MessageQueue.java:325)
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.os.Looper.loop(Looper.java:149)
> E/MethodChannel#holo#cameraSettingConfig(26667): at android.app.ActivityThread.main(ActivityThread.java:6842)
> E/MethodChannel#holo#cameraSettingConfig(26667): at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#holo#cameraSettingConfig(26667): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/MethodChannel#holo#cameraSettingConfig(26667): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
> E/flutter (26667): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Error 0xfffffc0e, null)
> E/flutter (26667): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
> E/flutter (26667): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
> E/flutter (26667):
> E/flutter (26667): #2 RtmpManager.startLive (package:flutter_rtmp/src/rtmp_manager.dart:46:30)
> E/flutter (26667): #3 _LiveTrmpContentState.build. (package:healthvideo/moudle/livestream/view/live_trmp_page.dart:83:34)
> E/flutter (26667): #4 _RawChipState._handleTap (package:flutter/src/material/chip.dart:1653:23)
> E/flutter (26667): #5 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
> E/flutter (26667): #6 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:789:36)
> E/flutter (26667): #7 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> E/flutter (26667): #8 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
> E/flutter (26667): #9 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
> E/flutter (26667): #10 BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
> E/flutter (26667): #11 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
> E/flutter (26667): #12 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
> E/flutter (26667): #13 PointerRouter._dispatchEventToRoutes. (package:flutter/src/gestures/pointer_router.dart:117:9)
> E/flutter (26667): #14 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
> E/flutter (26667): #15 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
> E/flutter (26667): #16 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
> E/flutter (26667): #17 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
> E/flutter (26667): #18 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> E/flutter (26667): #19 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> E/flutter (26667): #20 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> E/flutter (26667): #21 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> E/flutter (26667): #22 _rootRunUnary (dart:async/zone.dart:1138:13)
> E/flutter (26667): #23 _CustomZone.runUnary (dart:async/zone.dart:1031:19)
> E/flutter (26667): #24 _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
> E/flutter (26667): #25 _invoke1 (dart:ui/hooks.dart:273:10)
> E/flutter (26667): #26 _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
> E/flutter (26667):
> W/AMessage(26667): failed to deliver message as target handler 4 is gone.
> 
> 点击开始之后出现这个报错,并且无法推流
> 手机 魅族16th android 8.1 系统

感谢指出
这个问题在[yease/issues/334](https://github.com/begeekmyfriend/yasea/issues/334)中也没有完全解决,可以尝试一下
1.在 flutter_rtmp/android/srs/main/java/net/ossrs/yasea/SrsEncoder(611) 除断点调试
 a).查看支持的颜色转换列表

**Comment by muzhis** [comment]
十分感谢作者,我这边尝试一下,

**Comment by zlongCoding** [comment]
作者大大， 加入什么值的啊。我也有这个问题，但是不知道怎么弄

**Comment by GONDON** [comment]
Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'holo#cameraRtmpView') 这个报错事该怎么办呢？

**Comment by MEnigma** [comment]
> native_configure

可以先试一下
1.在 flutter_rtmp/android/srs/main/java/net/ossrs/yasea/SrsEncoder(611) 除断点调试
然后查看支持的色彩转换列表

**Comment by MEnigma** [comment]
> Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'holo#cameraRtmpView') 这个报错事该怎么办呢？

应该是iOS设备吧,在info.plist添加
<key>io.flutter.embedded_views_preview</key>
